src/Entity/Pagos.php
<?php

namespace App\Entity;

use App\Repository\PagosRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PagosRepository::class)]
class Pagos
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $fecha = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 20, scale: 0)]
    private ?string $pago_interes = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 20, scale: 0)]
    private ?string $abono_capital = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 20, scale: 0)]
    private ?string $pago_total = null;

    #[ORM\ManyToOne(inversedBy: 'pagos')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Prestamos $prestamo = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFecha(): ?\DateTimeInterface
    {
        return $this->fecha;
    }

    public function setFecha(\DateTimeInterface $fecha): static
    {
        $this->fecha = $fecha;

        return $this;
    }

    public function getPagoInteres(): ?string
    {
        return $this->pago_interes;
    }

    public function setPagoInteres(string $pago_interes): static
    {
        $this->pago_interes = $pago_interes;

        return $this;
    }

    public function getAbonoCapital(): ?string
    {
        return $this->abono_capital;
    }

    public function setAbonoCapital(string $abono_capital): static
    {
        $this->abono_capital = $abono_capital;

        return $this;
    }

    public function getPagoTotal(): ?string
    {
        return $this->pago_total;
    }

    public function setPagoTotal(string $pago_total): static
    {
        $this->pago_total = $pago_total;

        return $this;
    }

    public function getPrestamo(): ?Prestamos
    {
        return $this->prestamo;
    }

    public function setPrestamo(?Prestamos $prestamo): static
    {
        $this->prestamo = $prestamo;

        return $this;
    }
}

src/Entity/Prestamos.php
<?php

namespace App\Entity;

use App\Repository\PrestamosRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PrestamosRepository::class)]
class Prestamos
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 20, scale: 0)]
    private ?string $valorTotal = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $fechaPrestamo = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 10, scale: 0)]
    private ?string $porcentajeInteres = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 20, scale: 0)]
    private ?string $valorInteres = null;

    #[ORM\Column(length: 20)]
    private ?string $estado = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 20, scale: 0)]
    private ?string $deudaActual = null;

    #[ORM\Column(nullable: true)]
    private ?int $diaPago = null;

    #[ORM\ManyToOne(inversedBy: 'prestamos')]
    private ?Cliente $cliente = null;

    #[ORM\OneToMany(targetEntity: Pagos::class, mappedBy: 'prestamo')]
    private Collection $pagos;

    public function __construct()
    {
        $this->pagos = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getValorTotal(): ?string
    {
        return $this->valorTotal;
    }

    public function setValorTotal(string $valorTotal): static
    {
        $this->valorTotal = $valorTotal;

        return $this;
    }

    public function getFechaPrestamo(): ?\DateTimeInterface
    {
        return $this->fechaPrestamo;
    }

    public function setFechaPrestamo(\DateTimeInterface $fechaPrestamo): static
    {
        $this->fechaPrestamo = $fechaPrestamo;

        return $this;
    }

    public function getPorcentajeInteres(): ?string
    {
        return $this->porcentajeInteres;
    }

    public function setPorcentajeInteres(string $porcentajeInteres): static
    {
        $this->porcentajeInteres = $porcentajeInteres;

        return $this;
    }

    public function getValorInteres(): ?string
    {
        return $this->valorInteres;
    }

    public function setValorInteres(string $valorInteres): static
    {
        $this->valorInteres = $valorInteres;

        return $this;
    }

    public function getEstado(): ?string
    {
        return $this->estado;
    }

    public function setEstado(string $estado): static
    {
        $this->estado = $estado;

        return $this;
    }

    public function getDeudaActual(): ?string
    {
        return $this->deudaActual;
    }

    public function setDeudaActual(string $deudaActual): static
    {
        $this->deudaActual = $deudaActual;

        return $this;
    }

    public function getDiaPago(): ?int
    {
        return $this->diaPago;
    }

    public function setDiaPago(?int $diaPago): static
    {
        $this->diaPago = $diaPago;

        return $this;
    }

    public function getCliente(): ?Cliente
    {
        return $this->cliente;
    }

    public function setCliente(?Cliente $cliente): static
    {
        $this->cliente = $cliente;

        return $this;
    }

    /**
     * @return Collection<int, Pagos>
     */
    public function getPagos(): Collection
    {
        return $this->pagos;
    }

    public function addPago(Pagos $pago): static
    {
        if (!$this->pagos->contains($pago)) {
            $this->pagos->add($pago);
            $pago->setPrestamo($this);
        }

        return $this;
    }

    public function removePago(Pagos $pago): static
    {
        if ($this->pagos->removeElement($pago)) {
            // set the owning side to null (unless already changed)
            if ($pago->getPrestamo() === $this) {
                $pago->setPrestamo(null);
            }
        }

        return $this;
    }
}

src/Controller/PrestamosController.php
<?php

namespace App\Controller;

use App\Entity\Pagos;
use App\Entity\Prestamos;
use App\Form\PagosType;
use App\Form\PrestamoFormType;
use App\Repository\PrestamosRepository;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\Mapping\Entity;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;


#[Route('/d')]
class PrestamosController extends AbstractController
{
    #[Route('/prestamos', name: 'app_prestamos_list')]
    public function index(PrestamosRepository $prestamosRepository): Response
    {

        $prestamos = $prestamosRepository->findAll();

        return $this->render('prestamos/index.html.twig', [
            'prestamos' => $prestamos,
        ]);
    }

    #[Route('/prestamos/new', name: 'app_prestamos_new')]
    public function new(Request $request, EntityManagerInterface $em): Response
    {

        $prestamo = new Prestamos();
        // ...

        $form = $this->createForm(PrestamoFormType::class, $prestamo);


        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            // $form->getData() holds the submitted values
            // but, the original `$task` variable has also been updated
            $prestamo = $form->getData();
            $prestamo->setPorcentajeInteres(10);
            $prestamo->setValorInteres($prestamo->getValorTotal() * 0.10);
            $prestamo->setEstado("PENDIENTE");
            $prestamo->setDeudaActual($prestamo->getValorTotal() + ($prestamo->getValorTotal() * 0.10));
            $em->persist($prestamo);
            $em->flush();
            // ... perform some action, such as saving the task to the database

            return $this->redirectToRoute('app_prestamos_list');
        }
        return $this->render('prestamos/new.html.twig', [
            'form' => $form,
        ]);
    }

    #[Route('/prestamos/show/{id}', name: 'app_prestamos_show')]
    public function show(int $id, Request $request, EntityManagerInterface $em): Response
    {


        $prestamo = $em->getRepository(Prestamos::class)->find($id);
        $pagos = new Pagos();
        $pagos->setPagoInteres($prestamo->getValorInteres());
        $form = $this->createForm(PagosType::class, $pagos);
        $form->handleRequest($request);
        if ($form->isSubmitted()) {
            // $form->getData() holds the submitted values
            // but, the original `$task` variable has also been updated
            $pagos = $form->getData();
            $prestamo->addPago($pagos);
            $prestamo->setDeudaActual($prestamo->getDeudaActual() - $pagos->getPagoTotal());
            if ($prestamo->getDeudaActual() == 0) {
                $prestamo->setEstado("PAGADO");
            }

            $em->persist($pagos);
            $em->persist($prestamo);

            $em->flush();
            // ... perform some action, such as saving the task to the database
            return $this->redirectToRoute('app_prestamos_show', ["id" => $prestamo->getId()]);
        }

        return $this->render('prestamos/show.html.twig', [
            'prestamo' => $prestamo,
            'form' => $form,
        ]);
    }
}

templates/prestamos/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Prestamos
{% endblock %}

{% block body %}

	<div class="page-header">
		<div class="page-block">
			<div class="row align-items-center">
				<div class="col-md-8">
					<div class="page-header-title">
						<h5 class="m-b-10"><i class="fa-solid fa-file-invoice-dollar me-2"></i>Prestamos</h5>
						<p class="m-b-0">Gestion de Prestamos</p>
					</div>
				</div>				
			</div>
		</div>
	</div>
	<div class="container">


		<div class="my-3 row g-3">
			<div class="col-md-3">
				<a href="{{ path('app_prestamos_new') }}" type="button" class="text-nowrap btn btn-outline-secondary">
					<i class="fa-solid fa-person-circle-plus me-2"></i>
					<span class="">
						Crear Prestamo
					</span>
				</a>
			</div>
			<div class="col-md-6">
				<div class="input-group ">
					<input type="text" class="form-control" id="input-search-prestamo" placeholder="Buscar Cliente por nombre ...">

				</div>

			</div>

			<div class="col-md-3">

				<select class="form-select" id="filter-status-prestamo" aria-label="Default select example">
					<option selected>TODOS</option>
					<option value="PENDIENTE">PENDIENTE</option>
					<option value="PAGADO">PAGADO</option>
					<option value="CANCELADO">PAGADO</option>

				</select>
			</div>

		</div>


		<div class="table-responsive">

			<table class="table table-secondary table-striped" id="table-prestamos">
				<thead>
					<tr>
						<th scope="col">#</th>
						<th scope="col">Cliente</th>
						<th scope="col">Valor</th>
						<th scope="col">Estado</th>
						<th scope="col">Fecha</th>
						<th scope="col">#</th>
					</tr>
				</thead>
				<tbody>
					{% for prestamo in prestamos %}

						<tr>
							<th scope="row">{{ prestamo.id }}</th>
							<td>{{ prestamo.cliente.name }}</td>
							<td>{{ prestamo.valorTotal|number_format(2, ',', '.') }}</td>
							<td>
								<span class="badge bg-info">
									{{ prestamo.estado }}
								</span>
							</td>
							<td>{{ prestamo.fechaPrestamo|date('Y-m-d') }}</td>
							<td>
								<a href="{{ path('app_prestamos_show', {id: prestamo.id}) }}" type="button" class="btn btn-primary btn-sm">
									<i class="fa-regular fa-eye"></i>

								</a>

							</td>
						</tr>

					{% endfor %}
				</tbody>
			</table>
		</div>

	</div>

{% endblock %}

{% block javascripts %}
	{{ parent() }}
	 <script src="{{ asset('js/prestamos.index.js') }}"></script>


{% endblock %}

templates/prestamos/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Crear Nuevo Prestamos
{% endblock %}

{% block body %}

	<div class="container">

		{{ form(form) }}
		</div>


	{% endblock %}

	{% block javascripts %}
		{{ parent() }}
		 <script src="{{ asset('js/prestamos.index.js') }}"></script>
		 <script>
		$(document).ready(function() {

		    $('#prestamo_form_cliente').select2();
		});
		</script>

	{% endblock %}

templates/prestamos/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Prestamos
{% endblock %}

{% block body %}

	<div class="container " style="min-height:80vh">
		<div class="card ">
			<div class="card-body">
				<div class="d-flex gap-2 ">
					<span>Prestamo</span>
					<h3 scope="row">#{{ prestamo.id }}</h3>
				</div>
				<div class="d-flex gap-2 ">
					<span>Estado</span>
					<h3 scope="row">{{ prestamo.estado }}</h3>
				</div>
				<div class="d-flex gap-2 ">
					<span>Cliente</span>
					<h3 scope="row">{{ prestamo.cliente.name }}</h3>
				</div>
				<div class="d-flex gap-2 ">
					<span>Valor Prestamo</span>
					<h3 scope="row">
						COP
						{{ prestamo.valorTotal|number_format(1, '.', ',') }}
					</h3>
				</div>
				<div class="d-flex gap-2 ">
					<span>Pago x Interes</span>
					<h3 scope="row">
						COP
						{{ prestamo.valorInteres|number_format(1, '.', ',') }}
					</h3>
				</div>
				<div class="d-flex gap-2 ">
					<span>Deuda Actual</span>
					<h3 scope="row">
						COP
						{{ prestamo.deudaActual|number_format(1, '.', ',') }}
					</h3>
				</div>
				<div class="d-flex gap-2 ">
					<span>Porcenta de Interes</span>
					<h5 scope="row">{{ prestamo.porcentajeInteres }}%</h5>
				</div>
				<div class="d-flex gap-2 ">
					<span>Dia del mes para el pago</span>
					<h5 scope="row">{{ prestamo.diaPago }}
					</h5>
				</div>
				<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
					Crear Pago
				</button>

				<div class="table-responsive  mt-4">
					<table class="table table-sm">
						<thead>
							<tr>
								<th scope="col">#</th>
								<th scope="col">Fecha</th>
								<th scope="col">Valor Total</th>
								<th scope="col">Abono Interes</th>
								<th scope="col">Abono Capital</th>
							</tr>
						</thead>
						<tbody>

							{% for pago in prestamo.pagos %}

								<tr>

									<th scope="row">PG#{{ pago.id }}</th>
									<td>{{ pago.fecha|date('l | M-d-y') }}</td>

									<td>{{ pago.pagoTotal |number_format(2, ',', '.')  }}</td>
									<td>{{ pago.pagoInteres |number_format(2, ',', '.')  }}</td>
									<td>{{ pago.abonoCapital |number_format(2, ',', '.')  }}</td>


								</tr>

							{% endfor %}


						</tbody>
					</table>
				</div>


			</div>


		</div>


		<div class="modal fade" tabindex="-1" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true" aria-labelledby="exampleModalLabel" aria-hidden="true">
			<div class="modal-dialog">
				<div class="modal-content">
					<div class="modal-header">
						<h1 class="modal-title fs-5" id="exampleModalLabel">Crear Pago</h1>
						<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
					</div>
					<div class="modal-body">

						{{ form(form, {'action': path('app_prestamos_show', {'id': prestamo.id})}) }}

						</div>

					</div>
				</div>
			</div>
		</div>

	{% endblock %}


	{% block javascripts %}
		{{ parent() }}
		 <script>
										    // Inicializar Flatpickr
											var input1 = document.querySelector('#pagos_pago_interes');
										var input2 = document.querySelector('#pagos_abono_capital');
										var resultado = document.querySelector('#pagos_pago_total');
										
										// Escuchar el evento 'input' en los campos de entrada
										input1.addEventListener('input', actualizarResultado);
										input2.addEventListener('input', actualizarResultado);
										
										// Función para actualizar el resultado
										function actualizarResultado() {
										    // Obtener los valores de los campos de entrada
										    var valorInput1 = parseFloat(input1.value) || 0;
										    var valorInput2 = parseFloat(input2.value) || 0;
										
										    // Calcular la suma de los valores
										    var suma = valorInput1 + valorInput2;
										
										    // Asignar el resultado al campo de entrada 'resultado'
										    resultado.value = suma.toFixed(2); // Ajusta el número de decimales según sea necesario
										}
										
										</script>

	{% endblock %}